title: Executive Summary
author: Joaquin Soto 
email: joaquinsotorizzigmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is an assessment of impact for the P2 faced on Friday 28th.

# social links
twitter_username: @joaquinrizzi
github_username:  joaquinrizzi

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
